using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Stormancer.GameServers.Agent
{
    /// <summary>
    /// An application the agent should connect to.
    /// </summary>
    public class ApplicationConfigurationOptions : IEquatable<ApplicationConfigurationOptions>
    {
        /// <inheritdoc/>
        public override string ToString()
        {
            return $"{StormancerEndpoint}/{StormancerAccount}/{StormancerApplication}";
        }

        /// <inheritdoc/>
        public bool Equals(ApplicationConfigurationOptions? other)
        {
            if (other == null) return false;
            if (StormancerEndpoint != other.StormancerEndpoint) return false;
            if (StormancerAccount != other.StormancerAccount) return false;
            if (StormancerApplication != other.StormancerApplication) return false;

            return true;
        }

        /// <summary>
        /// Gets or sets the endpoint to connect to.
        /// </summary>
        public string? StormancerEndpoint { get; set; }

        /// <summary>
        /// Gets or sets the account of the app to connect to.
        /// </summary>
        public string? StormancerAccount { get; set; }

        /// <summary>
        /// Gets or sets the name of the app to connect to.
        /// </summary>
        public string? StormancerApplication { get; set; }

    }
    public class DockerAgentConfigurationOptions
    {
        public static string Section => "agent";
        public string? PublicIp { get; set; }

        public int MinPort { get; set; } = 40000;
        public int MaxPort { get; set; } = 40999;

        public int HttpPort { get; set; } = 30001;
        public long MaxMemory { get; set; }
        public float MaxCpu { get; set; }

        /// <summary>
        /// gets or sets the name of the agent.
        /// </summary>
        public string Id { get; set; } = Environment.MachineName;

        /// <summary>
        /// Gets or sets the path to the private key used to authentify the agent to applications.
        /// </summary>
        public string? PrivateKeyPath { get; set; }

        /// <summary>
        /// Gets or sets the password of the private key.
        /// </summary>
        public string? PrivateKeyPassword { get; set; }

        /// <summary>
        /// Gets or sets the path to memory dumps generated by containers on crash.
        /// </summary>
        public string? CorePath { get; set; }

        /// <summary>
        /// Gets or sets the region of the agent.
        /// </summary>
        public string? Region { get; set; }

        /// <summary>
        /// Gets or sets the list of applications the agent must advertises itself to.
        /// </summary>
        public Dictionary<string, ApplicationConfigurationOptions> Applications { get; set; } = new Dictionary<string, ApplicationConfigurationOptions>();

        /// <summary>
        /// Gets or sets the optional list of attributes advertised to applications.
        /// </summary>
        public Dictionary<string, string> Attributes { get; set; } = new Dictionary<string, string>();


        /// <summary>
        /// Validates the configuration.
        /// </summary>
        /// <returns></returns>
        public ConfigurationValidationModel Validate()
        {
            var model = new ConfigurationValidationModel();
            model.Success = true;


            return model;


        }

    }


}
