<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Company>Stormancer</Company>
		<Authors>Stormancer</Authors>
		<Version>0.1.0</Version>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<Description>Entity Framework storage for Stormancer leaderboard system.</Description>
		<Deterministic>true</Deterministic>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<Version>$(Version)-pre</Version>
	</PropertyGroup>

	<PropertyGroup>
		<PackageIcon>icon.png</PackageIcon>
	</PropertyGroup>
	<ItemGroup>
		<None Include="../../../../res/stormancer_128x128.png" Pack="true" PackagePath="\icon.png" />
	</ItemGroup>

	<ItemGroup>
		<NugetPackages Include="$(TargetDir)../$(ProjectName).$(Version).nupkg; $(TargetDir)../$(ProjectName).$(Version).snupkg" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Database\Stormancer.Server.Plugins.Database.EntityFrameworkCore.Npgsql\Stormancer.Server.Plugins.Database.EntityFrameworkCore.Npgsql.csproj" />
	  <ProjectReference Include="..\Stormancer.Server.Plugins.Leaderboards\Stormancer.Server.Plugins.Leaderboards.csproj" />
	</ItemGroup>

	<Target Name="PostPack" AfterTargets="Pack">
		<Copy SourceFiles="@(NugetPackages)" DestinationFolder="$(ProjectDir)../../../../output/packages" />
	</Target>

</Project>
