#pragma once

#define STORM_ENDPOINT "http://localhost"
#define STORM_ACCOUNT "account"
#define STORM_APPLICATION "application"
#define STORM_GALAXY_CLIENT_ID "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
#define STORM_GALAXY_CLIENT_SECRET "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
