#pragma once

#define STORM_ENDPOINT "http://localhost"
#define STORM_ACCOUNT "account"
#define STORM_APPLICATION "application"
#define STORM_EPIC_PRODUCT_ID "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
#define STORM_EPIC_SANDBOX_ID "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
#define STORM_EPIC_DEPLOYMENT_ID "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
#define STORM_EPIC_CLIENT_ID "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
#define STORM_EPIC_CLIENT_SECRET "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

#define STORM_EPIC_LOGIN_MODE "DevAuth" // POSSIBLE VALUES : "DevAuth" or "AccountPortal"
#define STORM_EPIC_DEVAUTH_CREDENTIALS_HOST "localhost:4567"
#define STORM_EPIC_DEVAUTH_CREDENTIALS_NAME "devAccount1"

#define STORM_CLIENT_VERSION "0.1.0"
