# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  ${{ if eq( variables['Build.SourceBranchName'], 'master' ) }}: 
    buildConfiguration: 'Release'
  ${{ if ne( variables['Build.SourceBranchName'], 'master' ) }}: 
    buildConfiguration: 'Debug'

steps:
- checkout: self
  lfs: true
  persistCredentials: true

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.x'
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'
- task: PowerShell@2
  displayName: 'Build'
  inputs:
    targetType: 'inline'
    script: |
      src/Stormancer.Plugins/build.ps1 --configuration $(buildConfiguration) --discord-token $env:discordToken -nuget-secret-key $env:nugetKey   
  env:
    nugetKey: $(nuget_ci_key)
    discordToken: $(discord_token)

    