#include "Lockstep.h"
#include "stormancer/IClientFactory.h"
#include "GameSessionViewModel.h"
#include "ViewModel.h"

LockstepViewModel::LockstepViewModel(GameSessionViewModel* parent)
	:parent(parent)
	, _clientId(parent->parent->id)
{

	
}

void LockstepViewModel::initialize()
{
	currentState = "";
	auto client = Stormancer::IClientFactory::GetClient(_clientId);
	_onStepSubscription  = client->dependencyResolver().resolve<Stormancer::Gameplay::LockstepApi>()->onStep.subscribe([this](Stormancer::Gameplay::Frame step)
	{
		for (auto& cmd : step.commands)
		{
			char c = (char)cmd.content[0];
			currentState = currentState + c;
		}
	});

	_onRollbackSubscription  = client->dependencyResolver().resolve<Stormancer::Gameplay::LockstepApi>()->onRollback.subscribe([this](Stormancer::Gameplay::RollbackContext& ctx)
	{
		Snapshot& current = snapshots.front();
		for (auto& snapshot : snapshots)
		{
			if (snapshot.frame > ctx.targetFrame)
			{
				break;
			}
			else
			{
				current = snapshot;
			}
		}

		currentState = current.state;
		ctx.restoredFrame = current.frame;

	});

	///Called when the peer needs to install a snapshot generated by another peer.
	_onInstallSnapshotSubscription = client->dependencyResolver().resolve<Stormancer::Gameplay::LockstepApi>()->onInstallSnapshot.subscribe([this](Stormancer::Gameplay::Snapshot& snapshot) 
	{
		this->gameplayTime = snapshot.gameplayTimeSeconds;
		this->currentState = std::string((const char*)snapshot.content.data(), snapshot.content.size());
			
	});

	//Called when the peer has to create a snapshot.
	_onCreateSnapshotSubscription = client->dependencyResolver().resolve<Stormancer::Gameplay::LockstepApi>()->onCreateSnapshot.subscribe([this](Stormancer::Gameplay::Snapshot& snapshot)
	{
		snapshot.content.resize(currentState.length());

		std::memcpy(snapshot.content.data(), currentState.c_str(), currentState.length());

	});

	_onStartSubscription = client->dependencyResolver().resolve<Stormancer::Gameplay::LockstepApi>()->onStart.subscribe([this]()
	{
		auto client = Stormancer::IClientFactory::GetClient(_clientId);
		auto logger = client->dependencyResolver().resolve<Stormancer::ILogger>();
		logger->log(Stormancer::LogLevel::Info, "lockstep", "OnStart called on time " + std::to_string(this->gameplayTime));
	});
}

bool LockstepViewModel::isEnabled()
{
	auto client = Stormancer::IClientFactory::GetClient(_clientId);

	auto api = client->dependencyResolver().resolve<Stormancer::Gameplay::LockstepApi>();
	return api->isEnabled();
}

void LockstepViewModel::Reset()
{
	currentState = "";
	snapshots.clear();
	Snapshot snapshot;
	snapshots.push_back(snapshot);
}

std::vector<::Stormancer::Gameplay::LockstepPlayer> LockstepViewModel::getPlayers()
{
	auto client = Stormancer::IClientFactory::GetClient(_clientId);

	auto api = client->dependencyResolver().resolve<Stormancer::Gameplay::LockstepApi>();
	return api->getPlayers();
}

void LockstepViewModel::addCommand(Stormancer::byte cmd)
{
	auto client = Stormancer::IClientFactory::GetClient(_clientId);

	auto api = client->dependencyResolver().resolve<Stormancer::Gameplay::LockstepApi>();

	api->pushCommand(&cmd, 1);

}

Stormancer::Gameplay::Time LockstepViewModel::getLockstepTime()
{
	auto client = Stormancer::IClientFactory::GetClient(_clientId);

	auto api = client->dependencyResolver().resolve<Stormancer::Gameplay::LockstepApi>();

	return api->getCurrentTime();
}

Stormancer::Gameplay::Time LockstepViewModel::getTargetTime()
{
	auto client = Stormancer::IClientFactory::GetClient(_clientId);

	auto api = client->dependencyResolver().resolve<Stormancer::Gameplay::LockstepApi>();

	return api->getTargetTime();
}

Stormancer::Gameplay::FrameDuration LockstepViewModel::getCommandLatency()
{
	auto client = Stormancer::IClientFactory::GetClient(_clientId);

	auto api = client->dependencyResolver().resolve<Stormancer::Gameplay::LockstepApi>();

	return api->getCommandLatency();
}

bool LockstepViewModel::isPaused()
{
	auto client = Stormancer::IClientFactory::GetClient(_clientId);

	auto api = client->dependencyResolver().resolve<Stormancer::Gameplay::LockstepApi>();

	return api->isPaused();
}

void LockstepViewModel::Pause(bool pause)
{ 
	auto client = Stormancer::IClientFactory::GetClient(_clientId);

	auto api = client->dependencyResolver().resolve<Stormancer::Gameplay::LockstepApi>();

	api->pause(pause);
}

void LockstepViewModel::tick(float delta)
{
	auto client = Stormancer::IClientFactory::GetClient(_clientId);

	auto api = client->dependencyResolver().resolve<Stormancer::Gameplay::LockstepApi>();

	auto gameplayDeltaTime = api->adjustTick(delta, delta);
	api->tick(gameplayDeltaTime,delta);

	this->gameplayTime += gameplayDeltaTime;
	this->realTime += delta;
	
	api->endFrame();
}

